### ISSUE TITLE
Stripe 82 fft parameter out of bounds

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#528] opened 2017-01-17 00:43 UTC
```validate_on_stripe82.jl``` is no longer working with fft.  I'm not sure what changed, and I was under the impression that @jeff-regier could run it.  Any ideas?

```
benchmark/stripe82/validate_on_stripe82.jl --fft
make: Nothing to be done for 'all'.
...
[1] DEBUG: source 137 [objid 1237663784734491064] took 3.4 seconds
[1] DEBUG: source 138 [objid 1237663784734491067] took 2.8 seconds
[1] DEBUG: source 139 [objid 1237663784734491068] took 2.0 seconds
ERROR: LoadError: AssertionError: all(param .>= sb.lb)
 in unsimplexify_parameter(::Array{Float64,1}, ::Celeste.Transform.SimplexBox) at /home/rgiordan/.julia/v0.5/Celeste/src/Transform.jl:167
```

**Comment by jeff-regier** [comment] 2017-01-17 00:49
If you run with it with more than 1 thread, it will skip the problematic
light source rather than throwing an exception. Not an ideal solution, but
it works.

**Comment by jeff-regier** [comment] 2017-01-17 00:50
Duplicate of #415

**Closed as completed by jeff-regier** 2017-01-17 00:50 UTC
