### ISSUE TITLE
PosDefException from neton_trust_region.jl

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#168] opened 2016-03-20 22:55 UTC
```
jregier@cori10~/Celeste/bin $ ./celeste.jl infer-nersc 164.39 164.5 39.11 39.5 .
...
20-Mar 15:47:47:INFO:root:3925 primary sources
20-Mar 15:47:47:INFO:root:2448 primary sources after MIN_FLUX cut
20-Mar 15:47:47:INFO:root:processing 512 sources in RA/Dec range
20-Mar 15:47:47:INFO:root:reading field (3840,1,69)
20-Mar 15:47:50:INFO:root:reading field (3840,1,70)
20-Mar 15:47:52:INFO:root:reading field (3900,6,269)
20-Mar 15:47:53:INFO:root:reading field (3900,6,270)
20-Mar 15:47:54:INFO:root:reading field (4469,6,343)
20-Mar 15:47:56:INFO:root:reading field (4469,6,344)
20-Mar 15:47:57:INFO:root:initializing celeste without PSF fit
Getting VP from sources.

20-Mar 15:48:41:INFO:root:fitting PSF for all relevant sources
ERROR: LoadError: Base.LinAlg.PosDefException(10)
 in chol! at linalg/cholesky.jl:28
 in solve_tr_subproblem! at /global/homes/j/jregier/.julia/v0.4/Celeste/src/newton_trust_region.jl:208
 in __newton_tr#21__ at /global/homes/j/jregier/.julia/v0.4/Celeste/src/newton_trust_region.jl:326
 in fit_psf at /global/homes/j/jregier/.julia/v0.4/Celeste/src/PSF.jl:121
 in fit_raw_psf_for_celeste at /global/homes/j/jregier/.julia/v0.4/Celeste/src/PSF.jl:702
 in get_source_psf at /global/homes/j/jregier/.julia/v0.4/Celeste/src/PSF.jl:221
 in fit_object_psfs! at /global/homes/j/jregier/.julia/v0.4/Celeste/src/ModelInit.jl:282
 in infer at /global/homes/j/jregier/.julia/v0.4/Celeste/src/api.jl:155
 in infer_nersc at /global/homes/j/jregier/.julia/v0.4/Celeste/src/api.jl:332
 in main at /global/u2/j/jregier/Celeste/bin/celeste.jl:36
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /global/u2/j/jregier/Celeste/bin/celeste.jl, in expression starting on line 42
```

**Comment by rgiordan** [comment] 2016-03-20 23:07
Is this the master branch, Jeff?

**Comment by rgiordan** [comment] 2016-03-20 23:11
PS I see this requires you to be on Cori.  Let me go see if I can log in -- I don't think I have.  If you can send a step to reproduce locally that will speed up my response time.

**Comment by rgiordan** [comment] 2016-03-20 23:20
How have you guys been running julia on Cori?

**Comment by jeff-regier** [comment] 2016-03-20 23:24
This is the single psf branch. I added `module load julia` to my
.bashrc.ext file

**Comment by rgiordan** [comment] 2016-03-21 00:35
I'm currently blocked by needing FITSIO.jl on Cori, so if you could change
your permissions, Jeff, or send me a tarball of your Cori julia 0.4
directory, I can try to take a look.

**Comment by rcthomas** [comment] 2016-03-21 02:24
If you do just `module load julia` at the command line on Cori you get 0.4.2.  If you do `module load julia/0.5.0-dev-2918` then you load the 0.5.0 commit we've been working on.

**Comment by rgiordan** [comment] 2016-03-21 17:18
It occurs to me that by "single psf branch" you might not mean the latest
in the PR.  There was a bug in the earlier PR that could cause this
problem, so take the latest.

-- Ryan.  Sent from a phone.  Nevertheless, all typos are deliberate.

**Comment by jeff-regier** [comment] 2016-03-21 17:48
I merged that PR last night. I can try recreating the problem now w master.
Is what's in master the latest code?

**Comment by rgiordan** [comment] 2016-03-21 17:49
My last PR was my latest work, yes.

-- Ryan.  Sent from a phone.  Nevertheless, all typos are deliberate.

**Comment by jeff-regier** [comment] 2016-03-21 18:10
I get the same error with master:

```
jregier@cori05~/Celeste $ git pull
Enter passphrase for key '/global/homes/j/jregier/.ssh/id_rsa': 
Already up-to-date.
jregier@cori05~/Celeste $ git status
# On branch master
nothing to commit (working directory clean)
jregier@cori05~/Celeste $ cd bin/
jregier@cori05~/Celeste/bin $ ./celeste.jl infer-nersc 164.39 164.5 39.11 39.5 .
...
21-Mar 11:04:23:INFO:root:fitting PSF for all relevant sources
ERROR: LoadError: Base.LinAlg.PosDefException(10)
 in chol! at linalg/cholesky.jl:28
 in solve_tr_subproblem! at /global/homes/j/jregier/.julia/v0.4/Celeste/src/newton_trust_region.jl:208
 in __newton_tr#21__ at /global/homes/j/jregier/.julia/v0.4/Celeste/src/newton_trust_region.jl:326
 in fit_psf at /global/homes/j/jregier/.julia/v0.4/Celeste/src/PSF.jl:121
 in fit_raw_psf_for_celeste at /global/homes/j/jregier/.julia/v0.4/Celeste/src/PSF.jl:702
 in get_source_psf at /global/homes/j/jregier/.julia/v0.4/Celeste/src/PSF.jl:221
 in fit_object_psfs! at /global/homes/j/jregier/.julia/v0.4/Celeste/src/ModelInit.jl:282
 in infer at /global/homes/j/jregier/.julia/v0.4/Celeste/src/api.jl:155
 in infer_nersc at /global/homes/j/jregier/.julia/v0.4/Celeste/src/api.jl:332
 in main at /global/u2/j/jregier/Celeste/bin/celeste.jl:36
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /global/u2/j/jregier/Celeste/bin/celeste.jl, in expression starting on line 42
```

**Comment by rgiordan** [comment] 2016-03-21 18:55
Could you please add a verbose option to infer and found out what it's
processing?

-- Ryan.  Sent from a phone.  Nevertheless, all typos are deliberate.

**Comment by jeff-regier** [comment] 2016-03-21 19:04
I don't see a verbose flag in infer (or infer_nersc). You're talking about
infer in api.jl?

Are you having trouble recreating the problem? I get it consistently.

**Comment by jeff-regier** [comment] 2016-03-21 19:05
Ah, I see a verbose flag in `maximize_f`. I'll set that.

**Comment by jeff-regier** [comment] 2016-03-21 19:24
I set verbose to true everywhere, but I don't see any new output.

**Comment by rgiordan** [comment] 2016-03-21 19:44
No, it's not in there.  I mentioned in another thread that if one of you
has some time to add a verbose option to infer that showed what object id,
and run camcol field you're on, it would be very helpful to me.  Could you
please add it?

**Comment by jeff-regier** [comment] 2016-03-21 20:33
I'm tied up with testing and implementing the scoring functions. I don't
have any special knowledge about the infer function. Can I leave this issue
to you?

**Comment by rgiordan** [comment] 2016-03-21 22:35
This is being caused by trying to fit a PSF for an object that doesn't occur in the image.  Probably extrapolating the PSF model beyond the edges of the image is causing the PSF image to look kind of crazy.

Specifically, the failing object is 
1237662226208063623 location (164.39681,    39.13884)
...which is being fit for a PSF in 
run = 3840, camcol = 1, field = 70
...whose corners are (164.402, 39.3165) and (164.539, 39.5742)

@kbarbary @rcthomas , you should probably change the logic of `infer_nersc` to only fit PSFs for images that will actually be used.

**Comment by rgiordan** [comment] 2016-03-21 23:17
Before we close this issue, please add a unit test for this as well.

**Comment by kbarbary** [comment] 2016-03-22 21:07
For a given object, if the center falls (just) off the edge of an image, but the object's range of influence extends onto the image, will the image still be used for this object?

**Comment by jeff-regier** [comment] 2016-03-22 21:08
Yes, that's what we'd want to happen

**Comment by kbarbary** [comment] 2016-03-22 21:15
@jeff-regier I'm asking about what the _optimizer_ currently does, so that we can ensure that the PSF is fit for the things it uses. (I'm assuming the answer is "yes".)

**Comment by rgiordan** [comment] 2016-03-22 21:22
@kbarbary , the optimizer's behavior is determined by the contents of tile_sources, which is populated by Modelnit, so it's under your control.

Recall that tile_sources is an array with the same dimensions as your TiledBlob -- there's an outer index for fields (previously one to five, now one to five \* the number of frames), and an inner index for tiles.  The patches array has the same dimensions.  If a source is in the tile_sources for a particular tile, you need to have the appropriate PSF for it in the corresponding patch.  Beyond that, the logic is up to you during initialization.

**Comment by jeff-regier** [comment] 2016-03-23 01:43
@rgiordan  I think this issue is still around. For `objid=1237662226208064362`, the error happens during iteration 14.

```
~/julia-2ac304dfba/bin/julia ./celeste.jl infer-nersc 164.39 164.5 39.11 39.5 . --logging=DEBUG
...
22-Mar 18:36:57:DEBUG:root:Fitting PSF for b=7, source=867, objid=1237662226208064362
22-Mar 18:36:57:DEBUG:root:
-----------------Iter 1
22-Mar 18:36:57:DEBUG:root:Interior
22-Mar 18:36:57:DEBUG:root:Root finding got m=-0.04720363670031677, interior=true with del
ta^2=100.0 and ||s||^2=1.0144391733822469
22-Mar 18:36:57:DEBUG:root:Got rho = 1.2569894776983288 from 0.10244198685762458 - 0.16177
646149901742 (diff = -0.05933447464139284), and m = -0.04720363670031677
22-Mar 18:36:57:DEBUG:root:Interior = true, delta = 10.0.
22-Mar 18:36:57:DEBUG:root:Keeping trust region the same.
22-Mar 18:36:57:DEBUG:root:Accepting improvement from f_prev=0.16177646149901742 f=0.10244
198685762458.
22-Mar 18:36:57:DEBUG:root:
...
-----------------Iter 14
22-Mar 18:36:57:DEBUG:root:Boundary
22-Mar 18:36:57:DEBUG:root:Easy case
22-Mar 18:36:57:DEBUG:root:---
22-Mar 18:36:57:DEBUG:root:lambda=0.07061455988936124 min_lambda=0.07061455988936124
22-Mar 18:36:57:DEBUG:root:lambda_1=-0.07061455988936123 [0.0,0.07052958281883713,0.070605
8454387885,0.07060587883818542,0.07060753901694133,0.07061425286516101,0.07061447664981978
,0.07061456983429827,0.07061500993886825,0.07061992913760093,0.07062247553872358,0.0706244
779158304]
Getting VP from sources.

ERROR: LoadError: Base.LinAlg.PosDefException(12)
 in chol! at linalg/cholesky.jl:28
 in solve_tr_subproblem! at /global/homes/j/jregier/.julia/v0.4/Celeste/src/newton_trust_r
egion.jl:201
 in __newton_tr#25__ at /global/homes/j/jregier/.julia/v0.4/Celeste/src/newton_trust_regio
n.jl:319
 in fit_psf at /global/homes/j/jregier/.julia/v0.4/Celeste/src/PSF.jl:121
 in fit_raw_psf_for_celeste at /global/homes/j/jregier/.julia/v0.4/Celeste/src/PSF.jl:702
 in get_source_psf at /global/homes/j/jregier/.julia/v0.4/Celeste/src/PSF.jl:221
 in fit_object_psfs! at /global/homes/j/jregier/.julia/v0.4/Celeste/src/ModelInit.jl:285
 in infer at /global/homes/j/jregier/.julia/v0.4/Celeste/src/api.jl:198
 in infer_nersc at /global/homes/j/jregier/.julia/v0.4/Celeste/src/api.jl:413
 in main at /global/u2/j/jregier/Celeste/bin/celeste.jl:37
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /global/u2/j/jregier/Celeste/bin/celeste.jl, in expression starting on line 
54
```

**Closed as completed** 2016-03-25 04:23 UTC
