### ISSUE TITLE
NaN in trust region code

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#138] opened 2016-03-08 00:37 UTC
@rgiordan -- Any idea what's happening here? There's an "out of bounds" warning followed by NaN-valued gradients in iteration 2 (and thereafter). It looks like the problem predates your commit that enforces bound constraints.

```
Processing band 1...
Processing band 2...
Processing band 3...
Processing band 4...
Processing band 5...
Done trimming.
Warning: r1[7][1] was out of bounds.
Warning: r1[7][2] was out of bounds.
f_evals: 1 value: -337.99099821351786
32x3 DataFrames.DataFrame
| Row | names     | val1     | grad1    |
|-----|-----------|----------|----------|
| 1   | "u_1"     | 0.16534  | 0.0      |
| 2   | "u_2"     | 0.601023 | 0.0      |
| 3   | "e_dev"   | 0.015    | 0.0      |
| 4   | "e_axis"  | 0.383083 | 0.0      |
| 5   | "e_angle" | 1.03506  | 0.0      |
| 6   | "e_scale" | 8.1312   | 0.0      |
| 7   | "r1_1"    | -1.0     | 0.718712 |
| 8   | "r1_2"    | -1.0     | 4.38648  |
⋮
| 24  | "c2_2_2"  | 0.01     | 34.3608  |
| 25  | "c2_3_2"  | 0.01     | 13.5302  |
| 26  | "c2_4_2"  | 0.01     | 30.6924  |
| 27  | "a_1"     | 0.2      | -1237.45 |
| 28  | "a_2"     | 0.8      | -114.376 |
| 29  | "k_1_1"   | 0.5      | -5.41762 |
| 30  | "k_2_1"   | 0.5      | -485.544 |
| 31  | "k_1_2"   | 0.5      | -19.9452 |
| 32  | "k_2_2"   | 0.5      | -144.714 |

=======================================


-----------------Iter 1
Boundary
Easy case
Root finding got m=-977.7798723798447, interior=false with delta^2=100.0 and ||s||^2=99.99999999999986
f_evals: 2 value: -48218.55716322409
32x3 DataFrames.DataFrame
| Row | names     | val1       | grad1     |
|-----|-----------|------------|-----------|
| 1   | "u_1"     | 0.16534    | 0.0       |
| 2   | "u_2"     | 0.601023   | 0.0       |
| 3   | "e_dev"   | 0.015      | 0.0       |
| 4   | "e_axis"  | 0.383083   | 0.0       |
| 5   | "e_angle" | 1.03506    | 0.0       |
| 6   | "e_scale" | 8.1312     | 0.0       |
| 7   | "r1_1"    | -1.0       | 3.5626    |
| 8   | "r1_2"    | -1.0       | 0.0472435 |
⋮
| 24  | "c2_2_2"  | 0.00999466 | 0.37082   |
| 25  | "c2_3_2"  | 0.00999801 | 0.148846  |
| 26  | "c2_4_2"  | 0.00999526 | 0.331803  |
| 27  | "a_1"     | 0.991384   | -48637.2  |
| 28  | "a_2"     | 0.0086162  | -164.162  |
| 29  | "k_1_1"   | 0.0143021  | -412.659  |
| 30  | "k_2_1"   | 0.985698   | -48900.1  |
| 31  | "k_1_2"   | 0.505983   | -0.281302 |
| 32  | "k_2_2"   | 0.494017   | -2.45414  |

=======================================

Got rho = -48.968655949598116 from 48218.55716322409 - 337.99099821351786 (diff = 47880.56616501057), and m = -977.7798723798447
Interior = false, delta = 10.0.
Shrinking trust region.
Rejecting improvement from f_prev = 337.99099821351786 to f=48218.55716322409

-----------------Iter 2
Boundary
Easy case
Root finding got m=NaN, interior=false with delta^2=NaN and ||s||^2=1.0745886990121294e22
f_evals: 3 value: NaN
32x3 DataFrames.DataFrame
| Row | names     | val1     | grad1 |
|-----|-----------|----------|-------|
| 1   | "u_1"     | 0.16534  | NaN   |
| 2   | "u_2"     | 0.601023 | NaN   |
| 3   | "e_dev"   | 0.015    | NaN   |
| 4   | "e_axis"  | 0.383083 | NaN   |
| 5   | "e_angle" | 1.03506  | NaN   |
| 6   | "e_scale" | 8.1312   | NaN   |
| 7   | "r1_1"    | -1.0     | NaN   |
| 8   | "r1_2"    | -1.0     | NaN   |
⋮
| 24  | "c2_2_2"  | 0.0001   | NaN   |
| 25  | "c2_3_2"  | 0.0001   | NaN   |
| 26  | "c2_4_2"  | 0.0001   | NaN   |
| 27  | "a_1"     | NaN      | NaN   |
| 28  | "a_2"     | 0.005    | NaN   |
| 29  | "k_1_1"   | 0.005    | NaN   |
| 30  | "k_2_1"   | 0.995    | NaN   |
| 31  | "k_1_2"   | NaN      | NaN   |
| 32  | "k_2_2"   | 0.005    | NaN   |

=======================================

Got rho = NaN from NaN - 337.99099821351786 (diff = NaN), and m = NaN
Interior = false, delta = NaN.
Keeping trust region the same.
Rejecting improvement from f_prev = 337.99099821351786 to f=NaN
```

**Comment by rgiordan** [comment] 2016-03-08 01:12
I'll take a look.  Have you checked the actual image?  Is it garbage or is
there something there?

-- Ryan.  Sent from a phone.  Nevertheless, all typos are deliberate.

**Comment by jeff-regier** [comment] 2016-03-08 01:28
I haven't checked, but it makes it through 2 iterations without NaNs, so I
doubt it's the image.

The problem seems to be pretty wide spread: most batches of 1% of a field
don't finish because of there error, at least in the run-camcol-field I'm
working with.

For example,

```
./celeste.jl infer ../test/data/ 4263 5 117 --part 4/100
```

**Comment by rgiordan** [comment] 2016-03-08 01:33
Its very first step is a crazy one, which points to a problem with the
image.  In my experience, Celeste does not handle ill-posed problems
gracefully.  And the catalog contains a fair number of non-objects (1%
sounds about right).  If the brightness is being corrected to be within the
transform bounds, this is probably one of them.

Could you send me steps to reproduce?

**Comment by jeff-regier** [comment] 2016-03-08 01:59
I just inadvertently committed a revised `test/data/Makefile` to master.
The upside to this is that if you pull the latest commit, you'll get a
Makefile you can use to recreate the problem:

Run `make` in `test/data`.

Then, in `bin`, run

```
./celeste.jl infer ../test/data/ 4263 5 117 --part 4/100
```

That's all the steps.

I don't think there are circumstances where we'd want Celeste to return NaN
as the objective value...on a crazy image Celeste may not to fit it well,
but ideally it would still only return numbers for the objective value.

**Comment by rgiordan** [comment] 2016-03-08 02:57
Just FYI, the Makefile doesn't include that run, camcol, and field.

**Comment by rgiordan** [comment] 2016-03-09 08:12
So I dug into it and this is a problem with a falsely discovered object in
the catalog.  The red band of the sky at the object location is attached --
it's just noise.

This object id is actually listed as having /negative/ flux in the
catalog.  Although I agree it would be nice if Celeste failed more
gracefully in cases like this, that requires some care, and in the meantime
we just shouldn't be attempting to fit objects like this.

Probably the best solution would be your idea of a third "non-source"
source type that Celeste can go to in cases like this.

Ryan

**Comment by jeff-regier** [comment] 2016-03-09 15:39
In a huge catalog there are always going to be some weird images that
differ from the model. So it sounds like you could be heading for a whole
series of hacks / quick fixes, if you try to screen out hard sources to fit
ahead of time, rather the making the objective function correct. (Shouldn't
the objective value always just have a real value?) Is it just that the
gradient is so large that it exceeds the maximum value of a 64 bit floating
point number?

**Comment by rgiordan** [comment] 2016-03-09 17:49
> In a huge catalog there are always going to be some weird images that
> differ from the model. 

Yes, it's important to make it as robust as possible.

> So it sounds like you could be heading for a whole series of hacks / quick fixes, if you try to screen out hard sources to fit ahead of time, rather the making the objective function correct.

Yes, I think there are two big things that will make the objective function more correct -- a third, non-source, and getting rid of the log approximation (so that the model really represents images additively).  I think we should address these in the context of an actual celestial object that fails (please let me know when you find one; I'm sure we will).  Even if the model were working perfect, I don't think it's unreasonable to just not attempt to fit objects with negative flux. 

> (Shouldn't the objective value always just have a real value?) Is it just that the gradient is so large that it exceeds the maximum value of a 64 bit floating point number?

It looks like the NaN is coming up in the trust region routine.  Since we have so much other stuff to do for SC, let me put off tracking it down in detail until we're looking at an actual problematic celestial object.

**Comment by rgiordan** [comment] 2016-03-09 20:37
I propose limiting to objects with a max flux greater than at least 2.  I've rendered all such objects in the run / camcol / field you were looking at, and though some objects look like they may be in excess of the noise, it's also probably true that Celeste is too high-powered a tool for getting information out of them.  (I'll send the images in an email to Dustin shortly.)

The fact is, Celeste is not currently good at detecting new images -- it's good at improving on existing catalog entries.   I think this is an important direction for future (post-SC) work.

**Comment by jeff-regier** [comment] 2016-03-09 20:47
OK, but let's leave this issue open then as a placeholder. We may need to
reorder some of the calculations for greater numerical stability.

**Comment by rgiordan** [comment] 2016-03-09 20:54
Really, there are two separate issues:
- Celeste doesn't work with a crappy image, or when being ask to detect
  absence / presence of an object
- The code doesn't handle NaNs gracefully

The latter is much easier to handle than the former.  Let's close this one
and make these two different issues.

**Comment by jeff-regier** [comment] 2016-03-09 21:08
I only meant for this issue to be about NaNs. Dealing with presence/absence is issue #101. Do you know what operation it is that first returns NaN? Is it an overflow thing? Often operations can be reordered to avoid overflows, e.g. divide a result before multiplying it by something big, not after.

**Comment by rgiordan** [comment] 2016-03-09 21:12
It is occurring in the trust region code, and no, I haven't dug into why
it's happening.  Sounds good, let's leave this open until someone does
that.  Perhaps the title of the issue could be changed to "NaN in trust
region code", since Celeste is not returning NaN gradients.

**Comment by rgiordan** [comment] 2016-03-11 20:09
I'm still getting this error with objid `1237662226208063538` even with the two NM filter.  I probably just need to make Celeste robust to NaNs in the trust region code.

**Comment by jeff-regier** [comment] 2016-03-11 20:19
It's too bad julia doesn't have a debugger yet. You'll probably want to use
print statements to track down the line where the calculation goes bad, and
then do things like reordering the calculations for numerical stability,
storing values on the log scale, etc.

**Comment by rgiordan** [comment] 2016-03-14 19:14
This was being caused by `Inf` values in `enforce_bounds!`, which was a shortsighted decision on my part.  I'll send a PR shortly.

**Comment by rgiordan** [comment] 2016-03-14 19:45
Fixed in https://github.com/jeff-regier/Celeste.jl/pull/150

**Closed as completed by rgiordan** 2016-03-14 19:45 UTC
