### ISSUE TITLE
initial single-node FLOPS measurements

### ISSUE THREAD

**Issue by rcthomas** [jeff-regier/Celeste.jl#516] opened 2017-01-11 16:44 UTC
Make a FLOPS measurement at the beginning of the hackathon.

**Comment by jeff-regier** [comment] 2017-01-20 21:31
Duplicate of #453, more or less. @andreasnoack please post a pre-hackathon measurement of single-node flops here once you have it.

**Comment by andreasnoack** [comment] 2017-01-21 21:35
I'll do what I can but Celeste is still not running on Julia master. We have many dependencies which are more or less broken right now. So far, I've fixed `StatsBase`, `Distributions`, `PDMats`, `DataStructures`, `FITSIO` and I'm working on `StaticArrays` right now.

**Comment by andreasnoack** [comment] 2017-01-30 17:54
I’m still trying to figure out how to correctly account for the masked operations on KNL so, meanwhile, I’ve done a count based on a Haswell run. According to Intel’s documentation, the total number of operations should be the same across architectures so the number should give us an indication of where we are. I’ve estimated the peakflop count from Julia’s `peakflops` function which is based on `dgemm`.

- Haswell `benchmark_one_light_source`, 1 thread: 1.48 (Float64) Gflops (4-5% of peak)
- KNL `benchmark_one_light_source`, 1 thread: 0.4 (Float64) Gflops (1-1.5% of peak)

The output from `parse_sde.sh` is printed below. Again, this is based on a run on Haswell.
```
Search stanza is "EMIT_GLOBAL_DYNAMIC_STATS"
elements_fp_single_1 = 526824415
elements_fp_single_4 = 0
elements_fp_single_8 = 19264000
elements_fp_single_16 = 0
elements_fp_double_1 = 3024446241
elements_fp_double_2 = 4197273640
elements_fp_double_4 = 547773644
elements_fp_double_8 = 0
--->Total single-precision FLOPs = 680936415
--->Total double-precision FLOPs = 13610088097
--->Total FLOPs = 14291024512
mem-read-1 = 5342292746
mem-read-2 = 685673007
mem-read-4 = 6221679782
mem-read-8 = 89702736644
mem-read-16 = 3828655154
mem-read-32 = 322392082
mem-read-64 = 2467664
mem-write-1 = 1194969639
mem-write-2 = 169033130
mem-write-4 = 4031375852
mem-write-8 = 43622913921
mem-write-16 = 3417872506
mem-write-32 = 2347895656
mem-write-64 = 0
--->Total Bytes read = 820955210624
--->Total Bytes written = 496460471763
--->Total Bytes = 1317415682387
```

**Comment by andreasnoack** [comment] 2017-01-30 19:42
Without fft, the rate on Haswell is 2.38 Gflops (~7% of peak)

Floating point counts for `benchmark_one_light_source` on Haswell without fft.
```
Search stanza is "EMIT_GLOBAL_DYNAMIC_STATS"
elements_fp_single_1 = 526479639
elements_fp_single_4 = 0
elements_fp_single_8 = 19264000
elements_fp_single_16 = 0
elements_fp_double_1 = 3615276807
elements_fp_double_2 = 3023248
elements_fp_double_4 = 95849744
elements_fp_double_8 = 0
--->Total single-precision FLOPs = 680591639
--->Total double-precision FLOPs = 4004722279
--->Total FLOPs = 4685313918
mem-read-1 = 4539707430
mem-read-2 = 553270979
mem-read-4 = 5201732173
mem-read-8 = 83437568245
mem-read-16 = 1343732627
mem-read-32 = 126254113
mem-read-64 = 2489310
mem-write-1 = 1009537942
mem-write-2 = 101884105
mem-write-4 = 3722257688
mem-write-8 = 40107070345
mem-write-16 = 2646568260
mem-write-32 = 778449963
mem-write-64 = 0
--->Total Bytes read = 719652893528
--->Total Bytes written = 404214390640
--->Total Bytes = 1123867284168
```

**Comment by Keno** [comment] 2017-01-30 19:43
We probably need to rebuild FFTW against the native arch. Try `MARCH=native` in Make.user and then rebuild FFTW

**Comment by andreasnoack** [comment] 2017-01-30 19:48
We use Intel's FFT library, not FFTW.

**Comment by Keno** [comment] 2017-01-30 19:49
Ah, never mind then.

**Comment by Keno** [comment] 2017-01-30 19:49
Can we confirm that the fft call itself has decent flops?

**Comment by jeff-regier** [comment] 2017-01-30 20:00
I think by "without fft", Andreas means `benchmark_one_light_source.jl` with `using_fft=false`. (Is that right?) That runs a whole different version of Celeste, a version that does a lot of exponentiation and doesn't use an FFT. So these latest results don't suggest that the FFT is bringing down our FLOPS average. (In fact, it's probably the only think keeping the FLOPS average up, when `using_fft=true`.)

Still, it would be interesting to see whether the FFT alone has decent flops.

**Comment by andreasnoack** [comment] 2017-01-30 21:01
How large are the arrays on which the fft is applied to?

**Comment by andreasnoack** [comment] 2017-01-31 01:36
Posting the fft results here as well. For a 2048x2048 `Matrix{Complex{Float64}}` I got about 7.44 Gflops for the 2d fft on Haswell which is about 20% of peak. For non-power-of-two arrays, the rate was significantly lower but that might be because of a more extensive plan calculation.

**Closed as completed** 2017-02-01 22:19 UTC
