### ISSUE TITLE
access to undefined reference

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#169] opened 2016-03-20 22:58 UTC
```
jregier@cori10~/Celeste/bin $ ./celeste.jl infer-nersc 164.3 164.35 39.1 39.15 .
...
20-Mar 15:56:44:INFO:root:field (3900,6,268): 808 entries
20-Mar 15:56:44:INFO:root:field (3900,6,269): 805 entries
20-Mar 15:56:44:INFO:root:field (3900,6,268): 725 primary entries
20-Mar 15:56:44:INFO:root:field (3900,6,269): 703 primary entries
20-Mar 15:56:45:INFO:root:1428 primary sources
20-Mar 15:56:45:INFO:root:1023 primary sources after MIN_FLUX cut
20-Mar 15:56:45:INFO:root:processing 24 sources in RA/Dec range
20-Mar 15:56:45:INFO:root:reading field (3900,6,268)
20-Mar 15:56:49:INFO:root:reading field (3900,6,269)
20-Mar 15:56:51:INFO:root:initializing celeste without PSF fit
Getting VP from sources.

20-Mar 15:56:59:INFO:root:fitting PSF for all relevant sources
20-Mar 15:57:17:INFO:root:processing source 275: objid= 1237662226207998451
Processing band 1...
Processing band 2...
Processing band 3...
Processing band 4...
Processing band 5...
Done trimming.
ERROR: LoadError: UndefRefError: access to undefined reference
 in elbo_likelihood! at /global/homes/j/jregier/.julia/v0.4/Celeste/src/ElboDeriv.jl:968
 in elbo_likelihood! at /global/homes/j/jregier/.julia/v0.4/Celeste/src/ElboDeriv.jl:1003
 in elbo_likelihood at /global/homes/j/jregier/.julia/v0.4/Celeste/src/ElboDeriv.jl:1046
 in anonymous at /global/homes/j/jregier/.julia/v0.4/Celeste/src/OptimizeElbo.jl:213
 in f_objective at /global/homes/j/jregier/.julia/v0.4/Celeste/src/OptimizeElbo.jl:107
 in f_value_grad at /global/homes/j/jregier/.julia/v0.4/Celeste/src/OptimizeElbo.jl:124
 in f_grad at /global/homes/j/jregier/.julia/v0.4/Celeste/src/OptimizeElbo.jl:148
 in f_grad! at /global/homes/j/jregier/.julia/v0.4/Celeste/src/OptimizeElbo.jl:152
 in fg! at /global/homes/j/jregier/.julia/v0.4/Optim/src/types.jl:197
 in __newton_tr#40__ at /global/homes/j/jregier/.julia/v0.4/Celeste/src/newton_trust_region.jl:298
 in maximize_f at /global/homes/j/jregier/.julia/v0.4/Celeste/src/OptimizeElbo.jl:226
 in infer at /global/homes/j/jregier/.julia/v0.4/Celeste/src/api.jl:170
 in infer_nersc at /global/homes/j/jregier/.julia/v0.4/Celeste/src/api.jl:332
 in main at /global/u2/j/jregier/Celeste/bin/celeste.jl:36
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /global/u2/j/jregier/Celeste/bin/celeste.jl, in expression starting on line 42
```

**Comment by rcthomas** [comment] 2016-03-21 20:48
I've been able to get this error too.  When I run with 0.25 0.26 0.25 0.26 I wind up with one source (objid 1237666408442495787) and it fails on the same line.  Sorry, it's not run, camcol, field but it's pretty minimal to reproduce.

This is with v0.5 on Cori.

**Comment by rgiordan** [comment] 2016-03-21 23:07
The cause of this is that `trim_source_tiles` has the number of bands hard-coded to five, and we're now using more than that number of images.

I'll put a fix into my last PR, but I'd like to assign this issue to @kbarbary until we have a multi-image unit test in place.

**Closed as completed** 2016-03-25 04:23 UTC
