### ISSUE TITLE
Restore single-machine optimization benchmarks

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#317] opened 2016-09-28 02:12 UTC
@jeff-regier , we used to have this, but I guess it got deleted in the refactor?  If you agree, I think it's something that belongs in `Celeste.jl/bin` for easy testing of code changes.

**Comment by jeff-regier** [comment] 2016-09-28 03:13
Duplicate of #251 ? Resurrecting the old benchmark script seems like a good idea, to make sure run time hasn't deteriorated,  but I seem to recall that its configuration wasn't so representative any more. Yeah, `bin` seems good for that. I wonder if what's in `staging` and `benchmarks` should be in `bin` too.

**Closed as completed** 2016-09-30 19:36 UTC
